on:
  push:
  pull_request:
jobs:
  test_mingw_on_windows:
    name: 'Test mingw on Windows'
    if: ${{ github.ref != 'refs/heads/ci-more' }}
    strategy:
      matrix:
        shared: ['ON', 'OFF']
        config: ['Release']
    runs-on: 'windows-latest'
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: 'Setup mingw'
        uses: 'msys2/setup-msys2@v2'
        with:
          install: mingw-w64-x86_64-cmake mingw-w64-x86_64-toolchain sed
      - name: 'Checkout repo'
        uses: actions/checkout@v2
      - name: 'CMake --help'
        run: cmake --help
      - name: 'CMake configure'
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_SHARED_LIBS=${{ matrix.shared }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
              -DFLATCC_INSTALL=ON -DCMAKE_INSTALL_PREFIX="$(cygpath -u "${{ github.workspace }}/prefix")" \
              -G "MinGW Makefiles"
      - name: 'CMake build'
        run: |
          cmake --build build --parallel
      - name: 'CTest'
        run: |
          cd build
          ctest -V -C ${{ matrix.config }}
      - name: 'Install'
        run: |
          cmake --build build --target install
      - name: 'Test installed flatcc prefix'
        run: |
          mkdir user && cd user
          cmake "${{ github.workspace }}/test/install_test" \
              -DCMAKE_PREFIX_PATH="$(cygpath -u "${{ github.workspace }}/prefix")" -G "MinGW Makefiles"
          cmake --build .
          ctest .
        env:
          PATH: '${{ github.workspace }}\prefix\bin'
